export const MockData = [
  {
    id: "g1",
    name: "구역A",
    location: "거제",
    temperature: 12.2,
    capacity: 15,
  },
  {
    id: "g2",
    name: "구역B",
    location: "거제",
    temperature: 11.6,
    capacity: 16,
  },
  {
    id: "g3",
    name: "구역C",
    location: "거제",
    temperature: 12.1,
    capacity: 20,
  },
  {
    id: "g4",
    name: "구역D",
    location: "통영",
    temperature: 13.8,
    capacity: 42,
  },
  {
    id: "g5",
    name: "구역E",
    location: "통영",
    temperature: 13.5,
    capacity: 45,
  },
  {
    id: "g6",
    name: "구역F",
    location: "거제",
    temperature: 11.5,
    capacity: 10,
  },
  {
    id: "g7",
    name: "구역G",
    location: "거제",
    temperature: 11.9,
    capacity: 17,
  },
  {
    id: "g8",
    name: "구역H",
    location: "고성",
    temperature: 12.0,
    capacity: 9,
  },
];
